Erp/Controllers/NodeLangController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using Erp.Data.Entities;

using Erp.Hubs;
using Erp.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace Erp.Controllers
{
    [Authorize(Roles = "Adminstrator")]
    public class NodeLangController : Controller
    {
        private readonly UserManager<ApplicationUser> _usermanager;
        private readonly IHubContext<DeployWorkflowHub> _hubcontext;
        private readonly DeployWorkflowHub _monitoringHub;
        private INodeLangRepository _nodeLangRepository;
        [HttpGet("monitoring")]
        public IActionResult Monitoring_Deployer()
        {
            return View();
        }
        [HttpGet("monitoring/{id}")]
        public IActionResult Monitoring_Workflow([FromRoute]string id)
        {
            ViewBag.Id = id;
            return View();
        }
        [HttpGet("GetWorkFlow/{id}")]
        public async Task<ActionResult<string>> GetWorkFlow([FromRoute]string id)
        {
            Guid guid = Guid.Parse(id);
            _nodeLangRepository.User = User;
            var workFlow = await _nodeLangRepository.GetById(id);
            string WorkFlowStr = workFlow.WorkFlow;
            return WorkFlowStr;
            
        }


        public NodeLangController(INodeLangRepository nodeLangRepository, UserManager<ApplicationUser> userManager, IHubContext<DeployWorkflowHub> hubcontext)
        {
            _usermanager = userManager;
            _hubcontext = hubcontext;
            _nodeLangRepository = nodeLangRepository;
        }
        [HttpPost("UploadWorkFlow")]
        public async Task<IActionResult> UploadWorkFlow(IFormFile file)
        {
            try
            {
                bool isCopied = false;
                if (file.Length > 0)
                {
                    string fileName = file.FileName;                   
                    string extension = Path.GetExtension(fileName);
                    if (extension == ".xml")
                    {
                        string workFlowStr = null;
                        string WorkFlowName = null;
                        string workFlowId = null;
                        using (Stream stream = file.OpenReadStream())
                        {
                            BinaryReader br = new BinaryReader(stream);
                            byte[] fileBytes = br.ReadBytes((int)stream.Length);
                            workFlowStr = Encoding.ASCII.GetString(fileBytes);

                            XmlDocument xmlDoc = new XmlDocument();
                            stream.Position = 0;
                            xmlDoc.Load(stream);
                            var element = xmlDoc.GetElementsByTagName("nodes")[0];
                            if (element == null)
                            {
                                throw new Exception("This xml file is not supported");
                            }
                            WorkFlowName = element.Attributes["name"].Value;
                            workFlowId = element.Attributes["id"].Value;
                            Console.WriteLine(WorkFlowName);
                        }
                        string filePath = Path.GetFullPath(
                            Path.Combine(Directory.GetCurrentDirectory(),
                                                        "wwwroot/WorkFlows"));
                        using (var fileStream = new FileStream(
                            Path.Combine(filePath, fileName),
                                           FileMode.Create))
                        {
                            await file.CopyToAsync(fileStream);
                            isCopied = true;


                        }
                        if (isCopied)
                        {

                            string idstr = workFlowId;
                           
                            Console.WriteLine(idstr);
                            _nodeLangRepository.User = User;
                            await _nodeLangRepository.Insert(new NodeLangWorkflow
                            {
                                Id = workFlowId,
                                Name = WorkFlowName,
                                WorkFlow = workFlowStr,
                                RuningInstances = 0
                            }
                            );
                            await _hubcontext.Clients.All.SendAsync("updateDeployList", idstr, WorkFlowName, workFlowStr);
                            return Ok();
                        }
                    }
                    else
                    {
                        throw new Exception("File must be either .xml");
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return BadRequest("error");

        }
    }
}

Erp/Views/NodeLang/Monitoring_Deployer.cshtml
@section Scripts
{
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/monitoringDeploy.js"></script>

}

<div style="background-color:aqua; float:left">
    <form id="uploadWorkflow" method="post" enctype="multipart/form-data" asp-controller="NodeLang" asp-action="UploadWorkFlow">
        <div class="form-group">
            <div class="col-md-10">
                <p>Upload one or more files using this form:</p>
                <input type="file" name="file" multiple>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Deploy">
            </div>
        </div>
    </form>

    <button style="float:left;" onclick="readXml()">show</button>
    <button style="float:left;" onclick="change()">change</button>
</div>
<div style="float:left">
    <ul id="workFlows"></ul>
</div>

Erp/Views/NodeLang/Monitoring_Workflow.cshtml
@{
    string id = ViewBag.Id;
}

@section Scripts
{
    <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/monitoringParser.js"></script>
    <script src="~/js/MonitoringExecution.js"></script>

}
<workflow id=@id>
    <div style="float:left">
        <ul id="runningInstances"></ul>
    </div>
    <div style="float:left">
        <svg id="WorkFlow" width="1000" height="1000" xmlns="http://www.w3.org/2000/svg">
            <defs>
                <marker id="arrowhead" viewBox="0 0 20 20" refX="11" refY="10" markerUnits="strokeWidth" markerWidth="10" markerHeight="10" orient="auto">
                    <path d="M 1 5 L 11 10 L 1 15 Z" style="fill: black; stroke-width: 1px; stroke-linecap: round; stroke-dasharray: 10000, 1; stroke: black;"></path>
                </marker>
            </defs>
        </svg>
    </div>
</workflow>